# ????????????????????
spring.sql.init.mode=never

# PostgreSQL ????Spring Boot 3.x ??????????????
spring.datasource.driver-class-name=org.postgresql.Driver

# ???????
# ???????? /postgres ????????? Navicat ?????????
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# ??????
spring.datasource.username=postgres

# ?????
# ???properties ?????????
spring.datasource.password=040209