spring.sql.init.mode=never
# ???????
spring.datasource.driver-class-name=org.postgresql.Driver

# ?????URL
spring.datasource.url=jdbc:postgresql://localhost:5432/Class

# ??????
spring.datasource.username=postgres

# ???????????
spring.datasource.password='040209'